USE [master]
GO
/****** Object:  Database [DoAn_lttq]    Script Date: 08/02/2023 4:12:16 CH ******/
CREATE DATABASE [DoAn_lttq]
 CONTAINMENT = NONE
 ON  PRIMARY 
( 
    NAME = N'DoAn_lttq', 
    FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DoAn_lttq.mdf', 
    SIZE = 8192KB, 
    MAXSIZE = UNLIMITED, 
    FILEGROWTH = 65536KB 
)
 LOG ON 
( 
    NAME = N'DoAn_lttq_log', 
    FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DoAn_lttq_log.ldf', 
    SIZE = 8192KB, 
    MAXSIZE = 2048GB, 
    FILEGROWTH = 65536KB 
)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DoAn_lttq] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DoAn_lttq].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DoAn_lttq] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DoAn_lttq] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DoAn_lttq] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DoAn_lttq] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DoAn_lttq] SET ARITHABORT OFF 
GO
ALTER DATABASE [DoAn_lttq] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DoAn_lttq] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DoAn_lttq] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DoAn_lttq] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DoAn_lttq] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DoAn_lttq] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DoAn_lttq] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DoAn_lttq] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DoAn_lttq] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DoAn_lttq] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DoAn_lttq] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DoAn_lttq] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DoAn_lttq] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DoAn_lttq] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DoAn_lttq] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DoAn_lttq] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DoAn_lttq] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DoAn_lttq] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DoAn_lttq] SET  MULTI_USER 
GO
ALTER DATABASE [DoAn_lttq] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DoAn_lttq] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DoAn_lttq] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DoAn_lttq] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DoAn_lttq] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DoAn_lttq] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DoAn_lttq] SET QUERY_STORE = OFF
GO
USE [DoAn_lttq]
GO
/****** Object:  Table [dbo].[BAN]    Script Date: 08/02/2023 4:12:16 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BAN](
	[IDBAN] [int] NOT NULL,
	[GIATIEN] [money] NULL,
	[TRANGTHAI] [bit] NULL,
 CONSTRAINT [PK_BAN] PRIMARY KEY CLUSTERED 
(
	[IDBAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DICHVU]    Script Date: 08/02/2023 4:12:16 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DICHVU](
	[IDDV] [int] NOT NULL,
	[TENDV] [nvarchar](50) NULL,
	[GIATIEN] [money] NULL,
	[HIENTHI] [bit] NULL,
 CONSTRAINT [PK_DICHVU] PRIMARY KEY CLUSTERED 
(
	[IDDV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON]    Script Date: 08/02/2023 4:12:16 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[IDHD] [int] NOT NULL,
	[IDNV] [int] NULL,
	[IDKH] [int] NULL,
	[GIOLAPHD] [datetime] NULL,
	[THANHTIEN] [money] NULL,
	[TRANGTHAI] [bit] NULL,
 CONSTRAINT [PK_HOADON] PRIMARY KEY CLUSTERED 
(
	[IDHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADONBAN]    Script Date: 08/02/2023 4:12:16 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADONBAN](
	[IDHD] [int] NULL,
	[IDBAN] [int] NULL,
	[GIOBATDAU] [datetime] NULL,
	[GIOKETTHUC] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADONDV]    Script Date: 08/02/2023 4:12:16 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADONDV](
	[IDHD] [int] NOT NULL,
	[IDDV] [int] NOT NULL,
	[SOLUONG] [int] NULL,
 CONSTRAINT [PK_HDDV] PRIMARY KEY CLUSTERED 
(
	[IDHD] ASC,
	[IDDV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 08/02/2023 4:12:16 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[IDKH] [int] NOT NULL,
	[HOTEN] [nvarchar](50) NULL,
	[DCHI] [nvarchar](100) NULL,
	[SODT] [char](10) NULL,
 CONSTRAINT [PK_KHACHHANG] PRIMARY KEY CLUSTERED 
(
	[IDKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 08/02/2023 4:12:16 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[IDNV] [int] NOT NULL,
	[HOTENNV] [nvarchar](50) NULL,
	[NGAYSINH] [datetime] NULL,
	[CCCD] [varchar](15) NULL,
	[MATKHAU] [varchar](32) NOT NULL,
	[QUYENADMIN] [bit] NULL,
	[TENDANGNHAP] [varchar](32) NOT NULL,
	[HIENTHI] [bit] NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[IDNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UNQ_CCCD] UNIQUE NONCLUSTERED 
(
	[CCCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NHANVIEN] ADD  CONSTRAINT [DF_NHANVIEN_MATKHAU]  DEFAULT ('12345678') FOR [MATKHAU]
GO
ALTER TABLE [dbo].[NHANVIEN] ADD  CONSTRAINT [DF_NHANVIEN_TENDANGNHAP]  DEFAULT ('nv00') FOR [TENDANGNHAP]
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [FK_HOADON_KHACHHANG] FOREIGN KEY([IDKH])
REFERENCES [dbo].[KHACHHANG] ([IDKH])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [FK_HOADON_KHACHHANG]
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [FK_HOADON_NHANVIEN] FOREIGN KEY([IDNV])
REFERENCES [dbo].[NHANVIEN] ([IDNV])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [FK_HOADON_NHANVIEN]
GO
ALTER TABLE [dbo].[HOADONBAN]  WITH CHECK ADD  CONSTRAINT [FK_HOADONBAN_BAN] FOREIGN KEY([IDBAN])
REFERENCES [dbo].[BAN] ([IDBAN])
GO
ALTER TABLE [dbo].[HOADONBAN] CHECK CONSTRAINT [FK_HOADONBAN_BAN]
GO
ALTER TABLE [dbo].[HOADONBAN]  WITH CHECK ADD  CONSTRAINT [FK_HOADONBAN_HOADON] FOREIGN KEY([IDHD])
REFERENCES [dbo].[HOADON] ([IDHD])
GO
ALTER TABLE [dbo].[HOADONBAN] CHECK CONSTRAINT [FK_HOADONBAN_HOADON]
GO
ALTER TABLE [dbo].[HOADONDV]  WITH CHECK ADD  CONSTRAINT [FK_HOADONDV_DICHVU] FOREIGN KEY([IDDV])
REFERENCES [dbo].[DICHVU] ([IDDV])
GO
ALTER TABLE [dbo].[HOADONDV] CHECK CONSTRAINT [FK_HOADONDV_DICHVU]
GO
ALTER TABLE [dbo].[HOADONDV]  WITH CHECK ADD  CONSTRAINT [FK_HOADONDV_HOADON] FOREIGN KEY([IDHD])
REFERENCES [dbo].[HOADON] ([IDHD])
GO
ALTER TABLE [dbo].[HOADONDV] CHECK CONSTRAINT [FK_HOADONDV_HOADON]
GO
/****** Object:  Trigger [dbo].[Thêm hóa đơn]    Script Date: 08/02/2023 4:12:16 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE trigger [dbo].[Thêm hóa đơn]
on [dbo].[HOADON]
after insert
as
begin
	declare @IDHD int;
	select @IDHD = IDHD
	from inserted
	update HOADON
	set THANHTIEN = 0
	where IDHD = @IDHD
end
GO
ALTER TABLE [dbo].[HOADON] ENABLE TRIGGER [Thêm hóa đơn]
GO
/****** Object:  Trigger [dbo].[Chỉnh sửa HD bàn]    Script Date: 08/02/2023 4:12:16 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create trigger [dbo].[Chỉnh sửa HD bàn]
on [dbo].[HOADONBAN]
after update
as
begin
	declare @IDHD int, @IDBAN int, @THOIGIAN datetime, @GIATIEN money;
	select @IDHD = IDHD, @IDBAN = IDBAN, @THOIGIAN = GIOKETTHUC - GIOBATDAU
	from deleted;
	select @GIATIEN = GIATIEN
	from BAN where IDBAN = @IDBAN;
	update HOADON
	set THANHTIEN -= (DATEPART(HOUR, @THOIGIAN) + DATEPART(MINUTE, @THOIGIAN)/60.0) * @GIATIEN
	select @IDHD = IDHD, @IDBAN = IDBAN, @THOIGIAN = GIOKETTHUC - GIOBATDAU
	from inserted;
	select @GIATIEN = GIATIEN
	from BAN where IDBAN = @IDBAN;
	update HOADON
	set THANHTIEN += (DATEPART(HOUR, @THOIGIAN) + DATEPART(MINUTE, @THOIGIAN)/60.0) * @GIATIEN
	where IDHD = @IDHD;
end
GO
ALTER TABLE [dbo].[HOADONBAN] ENABLE TRIGGER [Chỉnh sửa HD bàn]
GO
/****** Object:  Trigger [dbo].[Thêm HD bàn]    Script Date: 08/02/2023 4:12:17 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create trigger [dbo].[Thêm HD bàn]
on [dbo].[HOADONBAN]
after insert
as
begin
	declare @IDHD int, @IDBAN int, @THOIGIAN datetime, @GIATIEN money;
	select @IDHD = IDHD, @IDBAN = IDBAN, @THOIGIAN = GIOKETTHUC - GIOBATDAU
	from inserted;
	select @GIATIEN = GIATIEN
	from BAN where IDBAN = @IDBAN;
	update HOADON
	set THANHTIEN += (DATEPART(HOUR, @THOIGIAN) + DATEPART(MINUTE, @THOIGIAN)/60.0) * @GIATIEN
	where IDHD = @IDHD;
end
GO
ALTER TABLE [dbo].[HOADONBAN] ENABLE TRIGGER [Thêm HD bàn]
GO
/****** Object:  Trigger [dbo].[Xóa HD bàn]    Script Date: 08/02/2023 4:12:17 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create trigger [dbo].[Xóa HD bàn]
on [dbo].[HOADONBAN]
after delete
as
begin
	declare @IDHD int, @IDBAN int, @THOIGIAN datetime, @GIATIEN money;
	select @IDHD = IDHD, @IDBAN = IDBAN, @THOIGIAN = GIOKETTHUC - GIOBATDAU
	from deleted;
	select @GIATIEN = GIATIEN
	from BAN where IDBAN = @IDBAN;
	update HOADON
	set THANHTIEN -= (DATEPART(HOUR, @THOIGIAN) + DATEPART(MINUTE, @THOIGIAN)/60.0) * @GIATIEN
	where IDHD = @IDHD;
end
GO
ALTER TABLE [dbo].[HOADONBAN] ENABLE TRIGGER [Xóa HD bàn]
GO
/****** Object:  Trigger [dbo].[Chỉnh sửa hóa đơn DV]    Script Date: 08/02/2023 4:12:17 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create trigger [dbo].[Chỉnh sửa hóa đơn DV]
on [dbo].[HOADONDV]
after insert
as
begin
	declare @GIATIEN money, @SOLUONG int, @IDHD int;
	select @IDHD = IDHD, @SOLUONG = SOLUONG, @GIATIEN = GIATIEN
	from deleted i join DICHVU d on i.IDDV = d.IDDV;
	update HOADON
	set THANHTIEN -= @GIATIEN * @SOLUONG
	where IDHD = @IDHD
	select @IDHD = IDHD, @SOLUONG = SOLUONG, @GIATIEN = GIATIEN
	from inserted i join DICHVU d on i.IDDV = d.IDDV;
	update HOADON
	set THANHTIEN += @GIATIEN * @SOLUONG
	where IDHD = @IDHD
end
GO
ALTER TABLE [dbo].[HOADONDV] ENABLE TRIGGER [Chỉnh sửa hóa đơn DV]
GO
/****** Object:  Trigger [dbo].[Thêm hóa đơn DV]    Script Date: 08/02/2023 4:12:17 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE trigger [dbo].[Thêm hóa đơn DV]
on [dbo].[HOADONDV]
after insert
as
begin
	declare @GIATIEN money, @SOLUONG int, @IDHD int;
	select @IDHD = IDHD, @SOLUONG = SOLUONG, @GIATIEN = GIATIEN
	from inserted i join DICHVU d on i.IDDV = d.IDDV;
	update HOADON
	set THANHTIEN += @GIATIEN * @SOLUONG
	where IDHD = @IDHD
end
GO
ALTER TABLE [dbo].[HOADONDV] ENABLE TRIGGER [Thêm hóa đơn DV]
GO
/****** Object:  Trigger [dbo].[Xóa hóa đơn DV]    Script Date: 08/02/2023 4:12:17 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create trigger [dbo].[Xóa hóa đơn DV]
on [dbo].[HOADONDV]
after delete
as
begin
	declare @GIATIEN decimal, @SOLUONG int, @IDHD int;
	select @IDHD = IDHD, @SOLUONG = SOLUONG, @GIATIEN = GIATIEN
	from deleted d join DICHVU dv on d.IDDV = dv.IDDV;
	update HOADON
	set THANHTIEN -= @GIATIEN * @SOLUONG
	where IDHD = @IDHD
end
GO
ALTER TABLE [dbo].[HOADONDV] ENABLE TRIGGER [Xóa hóa đơn DV]
GO
/****** Object:  Trigger [dbo].[TRG_NHANVIEN_DELETE]    Script Date: 08/02/2023 4:12:17 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create trigger [dbo].[TRG_NHANVIEN_DELETE]
on [dbo].[NHANVIEN]
after delete
as
begin
	if (not exists(
		select *
		from NHANVIEN
		where QUYENADMIN = 1
	))
	begin
		rollback transaction;
		print N'Không thể xóa quản trị viên. Cần có tối thiểu 1 quản trị viên trong danh sách.';
	end
end
GO
ALTER TABLE [dbo].[NHANVIEN] ENABLE TRIGGER [TRG_NHANVIEN_DELETE]
GO
/****** Object:  Trigger [dbo].[TRG_NHANVIEN_INSERT]    Script Date: 08/02/2023 4:12:17 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create trigger [dbo].[TRG_NHANVIEN_INSERT]
on [dbo].[NHANVIEN]
after insert
as
begin
	declare @TENDANGNHAP varchar(64), @IDNV int;
	select @TENDANGNHAP = TENDANGNHAP, @IDNV = IDNV
	from inserted;
	if (exists(
		select *
		from NHANVIEN
		where TENDANGNHAP = @TENDANGNHAP and IDNV != @IDNV
	))
	begin
		rollback transaction;
		print N'Tên đăng nhập bị trùng. Vui lòng thử lại';
	end
end
GO
ALTER TABLE [dbo].[NHANVIEN] ENABLE TRIGGER [TRG_NHANVIEN_INSERT]
GO
/****** Object:  Trigger [dbo].[TRG_NHANVIEN_UPDATE]    Script Date: 08/02/2023 4:12:17 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create trigger [dbo].[TRG_NHANVIEN_UPDATE]
on [dbo].[NHANVIEN]
after update
as
if (update(TENDANGNHAP))
begin
	declare @TENDANGNHAP varchar(64), @IDNV int;
	select @TENDANGNHAP = TENDANGNHAP, @IDNV = IDNV
	from inserted;
	if (exists(
		select *
		from NHANVIEN
		where TENDANGNHAP = @TENDANGNHAP and IDNV != @IDNV
	))
	begin
		rollback transaction;
		print N'Tên đăng nhập bị trùng. Vui lòng thử lại';
	end
end
GO
ALTER TABLE [dbo].[NHANVIEN] ENABLE TRIGGER [TRG_NHANVIEN_UPDATE]
GO
USE [master]
GO
ALTER DATABASE [DoAn_lttq] SET  READ_WRITE 
GO
